<?php
foreach ($contenidos as $contenido)
{
    ?>
    <div class="my-3 p-3 bg-white rounded box-shadow">
    <h6 class="border-bottom border-gray pb-2 mb-0"><?php echo $contenido["titulo"]; ?></h6>
    <?php
    foreach ($contenido["divs"] as $div)
    {
        ?>
        <div class="media text-muted pt-3">
          <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark"><?php echo $div["titulo"]; ?></strong>
            <?php echo $div["texto"]; ?>
          </p>
        </div>
        <?php
    }
    ?>
    </div>
    <?php
}
?>